### ISSUE TITLE
семантика

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/podcast-html-css#1]
https://github.com/DenisPitsul/podcast-html-css/blob/89db02f31b425aa993a5825112216a24191d93a6/about.html#L109-L112
 я б взяла в подібних місцях замість div секцію, вона і заголовок свій має, і як додатковий плюс читатися краще буде

**Comment by DenisPitsul** [comment]
Resolved in commit: 
https://github.com/DenisPitsul/podcast-html-css/commit/20743eda975a58da6fffe7dea8a438d4dd7ff102
