### ISSUE TITLE
селектори

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/podcast-html-css#2]
https://github.com/DenisPitsul/podcast-html-css/blob/89db02f31b425aa993a5825112216a24191d93a6/assets/css/styles.css#L442
 - рекомендується максимально уникати комбінаторів, там де тільки це дійсно не жорстко стала структура. В подібних місцях краще навісити ще один клас на потрібний елемент і в ньому задати стилі.

**Comment by DenisPitsul** [comment]
Resolved in commit: 
https://github.com/DenisPitsul/podcast-html-css/commit/20743eda975a58da6fffe7dea8a438d4dd7ff102
