### ISSUE TITLE
файлова організація

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/podcast-html-css#3]
https://github.com/DenisPitsul/podcast-html-css/blob/89db02f31b425aa993a5825112216a24191d93a6/assets/css/styles.css#L888
- зручніше буде винести стилі для різних сторінок в різні файли. Можна також створити якийсь файл з універсальними стилями, які повторюються для різних сторінок.

**Comment by DenisPitsul** [comment]
Resolved in commit: 
https://github.com/DenisPitsul/podcast-html-css/commit/20743eda975a58da6fffe7dea8a438d4dd7ff102
